name: CI and Docker Publish
on: 
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  test:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Bogdanp/setup-racket@v1.9.1
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing shindig and its dependencies
        run: raco pkg install --no-docs --auto --name shindig
      - name: Compiling shindig and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps shindig
      - name: Testing shindig
        run: raco test -x -p shindig

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push dev image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shindig-dev:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shindig-dev:${{ github.sha }}
      
      # Then build and push shindig-package
      - name: Build and push package image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.package
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shindig-package:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shindig-package:${{ github.sha }}